#!/bin/bash

# Display help information
echo "Available bash scripts:"
echo ""
echo "Installation and Setup:"
echo "  bash scripts/install.sh              - Install dependencies"
echo "  bash scripts/install-dev.sh          - Install development dependencies"
echo "  bash scripts/dev-install.sh          - Install package in development mode"
echo "  bash scripts/setup-dev.sh            - Full development setup (clean, install, lint, format, test)"
echo ""
echo "Testing:"
echo "  bash scripts/test.sh                 - Run all tests with coverage"
echo "  bash scripts/quick-test.sh           - Run tests without coverage"
echo "  bash scripts/test-specific.sh FILE   - Run specific test file"
echo ""
echo "Code Quality:"
echo "  bash scripts/lint.sh                 - Lint code with flake8 and mypy"
echo "  bash scripts/format.sh               - Format code with black and isort"
echo "  bash scripts/clean.sh                - Clean cache and build files"
echo ""
echo "Examples:"
echo "  bash scripts/run-examples.sh         - Run all examples"
echo "  bash scripts/run-example.sh FILE     - Run specific example"
echo ""
echo "Help:"
echo "  bash scripts/help.sh                 - Show this help message"
